document.getElementById('year').textContent = new Date().getFullYear();

    const translations = {
      zh: { 'header.subtitle':'低价区·折扣·余额', 
      // 导航栏
      'nav.projects':'主要项目',
      'nav.support':'支持',
      // main
      'main.s1.title': '致所有玩家的一封信',
      'main.s1.p1': '亲爱的玩家们，',
      'main.s1.p2': '你是否曾因Steam国区高昂的定价而对心仪的游戏望而却步？\n你是否曾为抢不到绝版游戏或特定区域限定内容而懊恼不已？\n你是否觉得注册外区账号流程繁琐，充满未知风险？',
      'main.s1.p3': '我们，GameGlobal，完全理解你的烦恼！我们是一群由资深游戏玩家组成的团队，我们的使命就是打破地域与价格的壁垒，让每一位玩家都能以最实惠的价格、最便捷的方式，享受到全球游戏的乐趣。',
      'main.s2.title': '我们为您提供什么？',
      'main.s2.p1': '我们致力于打造一个一站式、安全可靠的Steam全球游戏服务平台。',
      'main.s2.s1.title': '1. 全球礼物代购 - 用最低成本，玩最多游戏！',
      'main.s2.s1.p1': '核心优势：利用全球各区域的定价差异，为您从低价区购买游戏，并以Steam官方礼物的形式发送给您。价格远低于国区，省钱就是硬道理！',
      'main.s2.s1.p2': '安全保障：所有礼物均通过Steam官方渠道发送，来源清晰，绝无黑卡风险，保障您的账号安全。',
      'main.s2.s1.p3': '便捷流程：只需提供您的Steam个人资料链接，选择游戏，支付后坐等收礼即可！',
      'main.s2.s2.title': '2. 全球账号售卖 - 一步到位，畅游世界！',
      'main.s2.s2.p1': '账号多样：我们提供已稳定入驻多个区域的Steam账号。无论是为了购买低价游戏，还是体验区域限定内容，总有一款适合你。',
      'main.s2.s2.p2': '安全可靠：所有账号均经过我们严格筛选和培养，资料齐全，初始邮箱可更改，最大限度保障您的账号所有权和安全。',
      'main.s2.s2.p3': '即买即用：购买后您将获得完整的账号信息，无需等待，立即开始您的全球游戏之旅。',
      'main.s2.s3.title': '3. 账号代注册 - 专业的事，交给专业的人！',
      'main.s2.s3.p1': '省时省力：繁琐的跨区注册流程、复杂的网络环境要求、难以获取的当地支付方式……这些都交给我们！',
      'main.s2.s3.p2': '高成功率：我们拥有成熟的注册方案和资源，确保为您成功注册一个干净、稳定的外区Steam账号。',
      'main.s2.s3.p3': '个性化服务：您可以选择指定的区域，我们甚至可以协助您完成首次充值或购买。',
      'main.s2.s4.title': '4. 余额交易 - 灵活变现，智慧充值！',
      'main.s2.s4.p1': '余额来源：提供来自社区市场交易、Steam充值卡等多种渠道的Steam钱包余额。',
      'main.s2.s4.p2': '超值折扣：相比官方渠道，我们的余额充值通常享有诱人的折扣，让您的每一分钱都花在刀刃上。',
      'main.s2.s4.p3': '多种用途：充值后的余额可用于购买游戏、DLC、内购道具，或在社区市场购买皮肤、贴纸等，灵活又方便。',
      'main.s2.s5.title': '为什么选择我们？',
      'main.s2.s5.p1': '玩家之心：我们本身就是玩家，深刻理解您的需求和担忧，服务体验从玩家角度出发。',
      'main.s2.s5.p2': '极致安全：我们将用户账号安全置于首位，所有交易流程都经过精心设计，力求透明、可追溯。',
      'main.s2.s5.p3': '透明定价：价格公开透明，无隐藏费用。您可以在购买前清晰了解所有成本。',
      'main.s2.s5.p4': '专业客服：7x24小时在线客服团队，随时为您解答疑问，处理订单中遇到的任何问题。',
      'main.s2.s5.p5': '隐私保护：我们郑重承诺，绝不会泄露您的任何个人及账号信息。',
      'main.s2.s6.title': '风险与提示',
      'main.s2.s6.p1': '我们深知，跨区交易存在一定的政策风险。因此，我们强烈建议您：使用小号进行跨区购买和游玩是更稳妥的选择。请勿频繁切换账号区域或进行异常的大额交易，以免触发Steam的风控机制。我们所做的一切，都是在遵守Steam用户协议的前提下，为您提供信息和服务。我们鼓励每位玩家在享受服务的同时，了解并自行承担潜在风险。',
      'main.s2.s7.title': '立即行动！',
      'main.s2.s7.p1': '不要再让价格和地域限制您的游戏体验！前往 GameGlobal，发现一个全新的游戏世界。现在注册，即可领取新用户专属优惠券！',
      'footer.notice':'服务仅面向需要低价区购买的用户。请遵守当地法律与平台条款。',
      'footer.tos':'条款 & 隐私',
      // 下拉菜单
      'dropdown.steamBalance':'Steam余额',
      'dropdown.steamAccount':'Steam账号',
      'dropdown.steamRegister':'Steam代注册',
      'dropdown.steamGift':'Steam代购',
      'dropdown.contact':'联系客服',
      'dropdown.about':'关于我们',
      'dropdown.comingSoon':'即将推出'},
      en: { 'header.subtitle':'Low Price Zones · Discounts · Balance',
      // 导航栏
      'nav.projects':'Main Projects',
      'nav.support':'Support',
      // main
      'main.s1.title': 'A Letter to All Players',
      'main.s1.p1': 'Dear players,',
      'main.s1.p2': 'Have you ever been discouraged by the high prices in your region Steam store?\nHave you ever missed out on limited edition or regional content?\nDo you find registering foreign accounts complicated and risky?',
      'main.s1.p3': 'We at GameGlobal completely understand your concerns! We are a team of experienced gamers dedicated to breaking down regional and pricing barriers, allowing every player to enjoy games globally at the best price and most convenient way.',
      'main.s2.title': 'What Can We Offer?',
      'main.s2.p1': 'We are committed to building a one-stop, safe, and reliable global Steam gaming service platform.',
      'main.s2.s1.title': '1. Global Gift Purchase - Lowest Cost, Maximum Games!',
      'main.s2.s1.p1': 'Core advantage: Utilizing pricing differences across regions, we purchase games from low-price zones and send them as official Steam gifts. Much cheaper than the local store, saving money is key!',
      'main.s2.s1.p2': 'Security: All gifts are sent via official Steam channels, with clear origin and no risk of black-market codes, ensuring account safety.',
      'main.s2.s1.p3': 'Convenience: Just provide your Steam profile link, choose your games, pay, and wait for the gifts!',
      'main.s2.s2.title': '2. Global Account Sales - Ready to Play Worldwide!',
      'main.s2.s2.p1': 'Variety: We offer Steam accounts registered in multiple regions. Whether for low-price games or region-exclusive content, there is one for everyone.',
      'main.s2.s2.p2': 'Reliability: All accounts are rigorously verified, information complete, initial emails can be changed, ensuring maximum account ownership and security.',
      'main.s2.s2.p3': 'Instant use: Receive full account details immediately and start your global gaming journey without delay.',
      'main.s2.s3.title': '3. Account Registration Service - Leave it to Professionals!',
      'main.s2.s3.p1': 'Time-saving: Complex cross-region registration processes, network requirements, and local payment limitations are all handled by us.',
      'main.s2.s3.p2': 'High success rate: We have mature registration solutions and resources to ensure a clean, stable foreign Steam account.',
      'main.s2.s3.p3': 'Personalization: You can select the region, and we can assist with initial recharge or purchases.',
      'main.s2.s4.title': '4. Balance Trading - Flexible and Smart Recharge!',
      'main.s2.s4.p1': 'Sources: Steam Wallet balances from market trades, Steam gift cards, and other channels.',
      'main.s2.s4.p2': 'Discounts: Compared with official channels, balance top-ups often enjoy attractive discounts.',
      'main.s2.s4.p3': 'Multiple uses: Use balance for games, DLC, in-game items, or market purchases, flexible and convenient.',
      'main.s2.s5.title': 'Why Choose Us?',
      'main.s2.s5.p1': 'We are players ourselves and deeply understand your needs and concerns.',
      'main.s2.s5.p2': 'Maximum security: Account safety is our priority, all processes are transparent and traceable.',
      'main.s2.s5.p3': 'Transparent pricing: All costs are clear before purchase.',
      'main.s2.s5.p4': 'Professional support: 24/7 customer service team available.',
      'main.s2.s5.p5': 'Privacy: We never leak personal or account information.',
      'main.s2.s6.title': 'Risks and Tips',
      'main.s2.s6.p1': 'We are aware of potential policy risks. It is recommended to use a secondary account for cross-region purchases and avoid frequent account switching or large unusual transactions.',
      'main.s2.s7.title': 'Act Now!',
      'main.s2.s7.p1': 'Don’t let price and region limit your gaming! Visit GameGlobal and explore a new world of games. Register now to receive a special new user coupon!',

      'footer.notice':'Services are intended only for users needing low-price zone purchases. Please comply with local laws and platform terms.',
      'footer.tos':'Terms & Privacy',
      // 下拉菜单
      'dropdown.steamBalance':'Steam Balance',
      'dropdown.steamAccount':'Steam Account',
      'dropdown.steamRegister':'Steam Registration',
      'dropdown.steamGift':'Steam Gift',
      'dropdown.contact':'Contact',
      'dropdown.about':'About',
      'dropdown.comingSoon':'Coming Soon'},
      es: { 'header.subtitle':'Zonas de bajo precio · Descuentos · Saldo',
      // 导航栏
      'nav.projects':'Proyectos',
      'nav.support':'Soporte',
      // main
      'main.s1.title': 'Una carta a todos los jugadores',
      'main.s1.p1': 'Estimados jugadores,',
      'main.s1.p2':'¿Alguna vez te has sentido desanimado por los altos precios en la tienda Steam de tu región?\n¿Alguna vez has perdido contenido de edición limitada o regional?\n¿Encuentras complicado y riesgoso registrar cuentas extranjeras?',
      'main.s1.p3':'Nosotros en GameGlobal entendemos completamente sus preocupaciones! Somos un equipo de jugadores experimentados dedicados a eliminar las barreras regionales y de precios, permitiendo que cada jugador disfrute de los juegos a nivel global al mejor precio y de la manera más conveniente. ',
      'main.s2.title': '¿Qué podemos ofrecer? ',
      'main.s2.p1': 'Estamos creando una plataforma GlobalSteam segura',
      'main.s2.s1.title': '1. Compra de Regalos Globales - El Costo Más Bajo, Máximo de Juegos! ',
      'main.s2.s1.p1': 'Ventaja principal: Aprovechando las diferencias de precios entre regiones, compramos juegos de zonas con precios más bajos y los enviamos como regalos oficiales de Steam. Mucho más económico que las tiendas locales, ahorrar dinero es clave! ',
      'main.s2.s1.p2': 'Seguridad: Todos los regalos se envían a través de canales oficiales de Steam, con origen claro y sin riesgo de códigos del mercado negro, garantizando la seguridad de la cuenta. ',
      'main.s2.s1.p3': 'Conveniencia: Solo proporciona el enlace de tu perfil de Steam, elige tus juegos, paga y espera a que lleguen los regalos!',
      'main.s2.s2.title':'2. Ventas de Cuenta Global - Listo para Jugar en Todo el Mundo! ',
      'main.s2.s2.p1': 'Variedad: Ofrecemos cuentas de Steam registradas en múltiples regiones. Ya sea para juegos de bajo precio o contenido exclusivo de región, hay una para todos. ',
      'main.s2.s2.p2': 'Confiable: Todas las cuentas son verificadas rigurosamente, la información es completa, los correos iniciales se pueden cambiar, garantizando la máxima propiedad y seguridad de la cuenta. ',
      'main.s2.s2.p3': 'Uso inmediato: Recibe los detalles completos de tu cuenta de inmediato y comienza tu viaje de gaming global sin demora. ',
      'main.s2.s3.title': '3. Servicio de Registro de Cuentas - Déjelo en manos de los profesionales! ',
      'main.s2.s3.p1': 'Ahorro de tiempo: Los complejos procesos de registro interregionales, los requisitos de red y las limitaciones de pago local son manejados por nosotros.',
      'main.s2.s3.p2': 'Alto índice de éxito: Contamos con soluciones y recursos maduros de registro para garantizar una cuenta de Steam extranjera limpia y estable. ',
      'main.s2.s3.p3': 'Personalización: Puedes seleccionar la región, y podemos ayudarte con la recarga inicial o compras. ',
      'main.s2.s4.title': '4. Trading de Balance - Recarga Flexible e Inteligente! ',
      'main.s2.s4.p1': 'Fuentes: Saldo de la billetera de Steam de transacciones en el mercado, tarjetas de regalo de Steam y otros canales. ',
      'main.s2.s4.p2': 'Descuentos: En comparación con los canales oficiales, los recargas de saldo a menudo disfrutan de atractivos descuentos. ',
      'main.s2.s4.p3': 'Múltiples usos: Utiliza el saldo para juegos, DLC, artículos en el juego o compras en el mercado, flexible y conveniente. ',
      'main.s2.s5.title': '¿Por qué elegirnos? ',
      'main.s2.s5.p1': 'Somos jugadores también y entendemos profundamente sus necesidades y preocupaciones. ',
      'main.s2.s5.p2': 'Máxima seguridad: La seguridad de la cuenta es nuestra prioridad, todos los procesos son transparentes y trazables. ',
      'main.s2.s5.p3': 'Precios transparentes: todos los costos son claros antes de la compra. ',
      'main.s2.s5.p4': 'Soporte profesional: equipo de servicio al cliente disponible las 24 horas del día, los 7 días de la semana. ',
      'main.s2.s5.p5': 'Privacidad: Nunca filtramos información personal o de la cuenta. ',
      'main.s2.s6.title': 'Riesgos y consejos',
      'principal.s2.s6.p1': 'Somos conscientes de los posibles riesgos de política. Se recomienda utilizar una cuenta secundaria para compras interregionales y evitar cambios frecuentes de cuenta o transacciones grandes y poco habituales. ',
      'main.s2.s7.title': 'Act Now! ',
      'main.s2.s7.p1': 'No dejes que el precio y la región limiten tu juego! Visita GameGlobal y explora un nuevo mundo de juegos. Regístrate ahora para recibir un cupón especial para nuevos usuarios! ',
      
        'footer.notice':'Los servicios están destinados solo a usuarios que necesitan compras en zonas de bajo precio. Cumpla con las leyes locales y los términos de la plataforma.',
      'footer.tos':'Términos & Privacidad',
      // 下拉菜单
      'dropdown.steamBalance':'Saldo Steam',
      'dropdown.steamAccount':'Cuenta Steam',
      'dropdown.steamRegister':'Registro Steam',
      'dropdown.steamGift':'Regalo Steam',
      'dropdown.contact':'Contacto',
      'dropdown.about':'Acerca de',
      'dropdown.comingSoon':'Próximamente'},
      ja: { 'header.subtitle':'低価格ゾーン・割引・残高',

      'nav.projects':'主なプロジェクト',
      'nav.support':'サポート',

      'main.s1.title': 'すべてのプレイヤーへの手紙',
      'main.s1.p1': 'プレイヤーの皆様へ、',
      'main.s1.p2': 'あなたの地域のSteamストアの高価格に挫折したことはありますか？\n限定版や地域限定コンテンツを逃したことはありますか？\n海外アカウントの登録が複雑でリスクが高いと感じますか？',
      'main.s1.p3': 'ゲームグローバルのスタッフは皆さんの懸念を完全に理解しています！私たちは経験豊富なゲーマーのチームで、地域や価格の障壁を取り払い、すべてのプレイヤーが最良の価格で最も便利な方法で世界中でゲームを楽しむことを目指しています。',
      'main.s2.title': '私たちが提供できるもの',
      'main.s2.p1': '我々は安全なグローバル・スチームプラットフォームを作成しています',
      'main.s2.s1.title': '1. グローバルギフト購入 - 最低コストで最大ゲーム数！',
      'main.s2.s1.p1': 'コアアドバンテージ：地域間の価格差を利用し、低価格地域からゲームを購入し、公式のSteamギフトとして送付します。地元の店よりずっと安価で、お金を節約するのに最適！',
      'main.s2.s1.p2': 'セキュリティ: すべてのギフトは公式のSteamチャンネルを通じて送信され、明確な出所があり、闇市コードのリスクがなく、アカウントの安全性が確保されています。',
      'main.s2.s1.p3': '便利性：Steamプロフィールリンクを提供し、ゲームを選択して支払い、ギフトを待つだけ！',
      'main.s2.s2.title': '2. グローバルアカウント販売 - 世界中でプレイ準備完了！',
      'main.s2.s2.p1': 'バリエーション: 我々は複数の地域で登録されたSteamアカウントを提供しています。安価なゲームでも地域限定コンテンツでも、誰にでもお使いいただけるものがあります。',
      'main.s2.s2.p2': '信頼性：すべてのアカウントは厳格に検証され、情報が完全で、初期のメールは変更可能で、アカウントの所有権とセキュリティを最大限に確保しています。',
      'main.s2.s2.p3': '即時利用: 完全なアカウント詳細をすぐに受け取り、遅滞なくグローバルゲームの旅を始めることができます。',
      'main.s2.s3.title': '3. アカウント登録サービス - 専門家に任せましょう!',
      'main.s2.s3.p1': '時間短縮：複雑なクロスリージョン登録プロセス、ネットワーク要件、およびローカル決済の制限はすべて弊社で対応いたします。',
      'main.s2.s3.p2': '高い成功率：成熟した登録ソリューションとリソースを備えており、クリーンで安定した海外のSteamアカウントを確保できます。',
      'main.s2.s3.p3': 'パーソナライズ：地域を選択でき、初回のチャージや購入にご協力いたします。',
      'main.s2.s4.title': '4. バランス取引 - 柔軟でスマートなチャージ！',
      'main.s2.s4.p1': '情報源: 市場取引、Steamギフトカード、その他のチャネルからのSteamウォレット残高。',
      'main.s2.s4.p2': '割引：公式チャンネルと比較して、残高チャージには魅力的な割引が適用されることが多い。',
      'main.s2.s4.p3': '多用途：ゲーム、DLC、インゲームアイテム、またはマーケットでの購入にバランスを活用し、柔軟で便利です。',
      'main.s2.s5.title': 'なぜ私たちを選ぶのか？',
      'main.s2.s5.p1': '私たちは自分自身がプレイヤーであり、お客様のニーズや懸念を深く理解しています。',
      'main.s2.s5.p2': '最高のセキュリティ：お客様のアカウントの安全が当社の最優先事項であり、すべてのプロセスは透明で追跡可能です。',
      'main.s2.s5.p3': '透明な価格設定：購入前にすべての費用が明確です。',
      'main.s2.s5.p4': 'プロフェッショナルサポート：24時間365日のカスタマーサービスチームが対応。',
      'main.s2.s5.p5': 'プライバシー: 私たちは個人情報やアカウント情報を一切漏らしません。',
      'main.s2.s6.title': 'リスクと注意点',
      'main.s2.s6.p1': '我々は潜在的なポリシーリスクを認識しています。クロスリージョン購入にはサブアカウントの使用を推奨し、頻繁なアカウント切り替えや大口の異常取引を避けるようにお願いします。',
      'main.s2.s7.title': '今すぐ行動せよ!',
      'main.s2.s7.p1': '価格や地域にゲームの楽しみを制限させないでください！GameGlobalにアクセスして、新しいゲームの世界を探検しましょう。今すぐ登録して、新規ユーザー特典クーポンをゲット！',


      'footer.notice':'サービスは低価格ゾーンの購入が必要なユーザーのみを対象としています。現地の法律およびプラットフォーム規約を遵守してください。',
      'footer.tos':'利用規約 & プライバシー',

      'dropdown.steamBalance':'Steam残高',
      'dropdown.steamAccount':'Steamアカウント',
      'dropdown.steamRegister':'Steam登録',
      'dropdown.steamGift':'Steamギフト',
      'dropdown.contact':'お問い合わせ',
      'dropdown.about':'会社概要','dropdown.comingSoon':'近日公開'},
      fr: { 'header.subtitle':'Zones à bas prix · Remises · Solde',

      'nav.projects':'Projets principaux',
      'nav.support':'Support',

      'main.s1.title': 'Une Lettre à Tous les Joueurs',
      'main.s1.p1': 'Chers joueurs,',
      'main.s1.p2': 'Avez-vous jamais été découragé par les prix élevés dans la boutique Steam de votre région ?\nAvez-vous jamais manqué une édition limitée ou du contenu régional ?\nEstimez-vous que l enregistrement de comptes étrangers est compliqué et risqué ?',
      'main.s1.p3': 'À GameGlobal, nous comprenons parfaitement vos préoccupations ! Nous sommes une équipe de gamers expérimentés dédiée à briser les barrières régionales et tarifaires, permettant à chaque joueur de profiter des jeux à travers le monde au meilleur prix et de la manière la plus pratique.',
      'main.s2.title': 'Quels sont nos services ?',
      'main.s2.p1': 'Nous créons une plateforme GlobalSteam sécurisée',
      'main.s2.s1.title': '1. Achat global de cadeaux - Le coût le plus bas, le maximum de jeux !',
      'main.s2.s1.p1': 'Avantage principal : En exploitant les différences de prix entre les régions, nous achetons des jeux dans les zones à bas prix et les envoyons sous forme de cadeaux Steam officiels. Beaucoup moins cher que les magasins locaux, économiser de l argent est la clé !',
      'main.s2.s1.p2': 'Sécurité : Tous les cadeaux sont envoyés via les canaux officiels de Steam, avec une origine claire et aucun risque de codes sur le marché noir, garantissant ainsi la sécurité du compte.',
      'main.s2.s1.p3': 'Confort : Il vous suffit de fournir le lien de votre profil Steam, de choisir vos jeux, de payer et d attendre que les cadeaux soient envoyés !',
      'main.s2.s2.title': '2. Ventes de Compte Global - Prêt à Jouer Partout dans le Monde !',
      'main.s2.s2.p1': 'Variété : Nous proposons des comptes Steam enregistrés dans plusieurs régions. Que ce soit pour des jeux à bas prix ou des contenus exclusifs à une région, il y en a pour tout le monde.',
      'main.s2.s2.p2': 'Fiabilité : Tous les comptes sont rigoureusement vérifiés, les informations sont complètes, les premiers e-mails peuvent être modifiés, garantissant une propriété et une sécurité maximales des comptes.',
      'main.s2.s2.p3': 'Utilisation instantanée : Obtenez immédiatement les détails complets de votre compte et commencez votre aventure de jeu mondial sans délai.',
      'main.s2.s3.title': '3. Service d’inscription de compte - Faites-le faire par des professionnels !',
      'main.s2.s3.p1': 'Gain de temps : Nous gérons les processus complexes d enregistrement inter-régions, les exigences réseau et les limitations de paiement local.',
      'main.s2.s3.p2': 'Taux de réussite élevé : Nous disposons de solutions et de ressources matures d’inscription pour garantir un compte Steam étranger propre et stable.',
      'main.s2.s3.p3': 'Personnalisation : Vous pouvez sélectionner la région, et nous pouvons vous aider avec le recharge initial ou les achats.',
      'main.s2.s4.title': '4. Balance Trading - Recharge flexible et intelligente!',
      'main.s2.s4.p1': 'Sources : Solde de l\'e-wallet Steam provenant des transactions sur le marché, cartes-cadeaux Steam et d\'autres canaux.',
      'main.s2.s4.p2': 'Remises : Par rapport aux canaux officiels, les recharges de solde bénéficient souvent de remises attractives.',
      'main.s2.s4.p3': 'Utilisations multiples : Utilisez le solde pour les jeux, les DLC, les objets en jeu ou les achats sur le marché, flexible et pratique.',
      'main.s2.s5.title': 'Pourquoi nous choisir ?',
      'main.s2.s5.p1': 'Nous sommes également des joueurs et comprenons profondément vos besoins et préoccupations.',
      'main.s2.s5.p2': 'Sécurité maximale : La sécurité de votre compte est notre priorité, tous les processus sont transparents et traçables.',
      'main.s2.s5.p3': 'Tarification transparente : Tous les coûts sont clairs avant l achat.',
      'main.s2.s5.p4': 'Support professionnel : une équipe de service client disponible 24h/24 et 7j/7.',
      'main.s2.s5.p5': 'Confidentialité : Nous ne divulguons jamais d informations personnelles ou de compte.',
      'main.s2.s6.title': 'Risques et Conseils',
      'main.s2.s6.p1': 'Nous sommes conscients des risques potentiels liés aux politiques. Il est recommandé d utiliser un compte secondaire pour les achats interrégionaux et d éviter les changements fréquents de compte ou les transactions importantes inhabituelles.',
      'main.s2.s7.title': 'Agissez maintenant !',
      'main.s2.s7.p1': 'Ne laissez pas le prix et la région limiter vos jeux ! Visitez GameGlobal et explorez un nouveau monde de jeux. Inscrivez-vous maintenant pour recevoir un coupon spécial pour les nouveaux utilisateurs !',


      'footer.notice':'Les services sont destinés uniquement aux utilisateurs ayant besoin d’achats dans les zones à bas prix. Veuillez respecter les lois locales et les conditions de la plateforme.',
      'footer.tos':'Conditions & Confidentialité',

      'dropdown.steamBalance':'Solde Steam',
      'dropdown.steamAccount':'Compte Steam',
      'dropdown.steamRegister':'Inscription Steam',
      'dropdown.steamGift':'Cadeau Steam',
      'dropdown.contact':'Contact',
      'dropdown.about':'À propos',
      'dropdown.comingSoon':'Bientôt'},
      de: { 'header.subtitle':'Niedrigpreis-Zonen · Rabatte · Guthaben',

      'nav.projects':'Hauptprojekte',
      'nav.support':'Unterstützung',

      'main.s1.title': 'Ein Brief an alle Spieler',
      'main.s1.p1': 'Liebe Spieler,',
      'main.s1.p2': 'Haben Sie sich je durch die hohen Preise im Steam-Shop Ihres Landes entmutigen lassen?\nHaben Sie je limitierte Editionen oder regionale Inhalte verpasst?\nFinden Sie die Registrierung ausländischer Konten kompliziert und riskant?',
      'main.s1.p3': 'Wir bei GameGlobal verstehen Ihre Bedenken voll und ganz! Wir sind ein Team von erfahrenden Spielern, das sich darauf konzentriert, regionale und Preisbarrieren abzubauen, damit jeder Spieler weltweit die besten Preise und die bequemste Art genießen kann, Spiele zu spielen.',
      'main.s2.title': 'Was bieten wir an?',
      'main.s2.p1': 'Wir schaffen eine sichere GlobalSteam-Plattform',
      'main.s2.s1.title': '1. Globale Geschenkkauf - Niedrigste Kosten, maximale Spiele!',
      'main.s2.s1.p1': 'Hauptvorteil: Durch die Nutzung von Preisunterschieden in verschiedenen Regionen kaufen wir Spiele aus Preisnachläufen und senden sie als offizielle Steam-Geschenke. Weitaus günstiger als lokale Geschäfte, Geld sparen ist der Schlüssel!',
      'main.s2.s1.p2': 'Sicherheit: Alle Geschenke werden über offizielle Steam-Kanäle versendet, mit klarem Ursprung und keinem Risiko für Schwarzmarkt-Codes, was die Kontosicherheit gewährleistet.',
      'main.s2.s1.p3': 'Bequemkeit: Führen Sie einfach Ihren Steam-Profil-Link an, wählen Sie Ihre Spiele, zahlen Sie und warten Sie auf die Geschenke!',
      'main.s2.s2.title': '2. Global Account Sales - Ready to Play Worldwide!',
      'main.s2.s2.p1': 'Vielfalt: Wir bieten Steam-Konten, die in mehreren Regionen registriert sind. Ob für günstige Spiele oder regionale Exklusivinhalte – für jeden ist etwas dabei.',
      'main.s2.s2.p2': 'Zuverlässigkeit: Alle Konten werden streng verifiziert, die Informationen sind vollständig, die ersten E-Mails können geändert werden, was die maximale Kontenbesitzsicherheit und -sicherheit gewährleistet.',
      'main.s2.s2.p3': 'Sofortige Nutzung: Erhalten Sie sofort die vollständigen Kontodetails und starten Sie Ihre globale Gaming-Reise ohne Verzögerung.',
      'main.s2.s3.title': '3. Kontoregisterungsdienst - Lassen Sie es Profis sein!',
      'main.s2.s3.p1': 'Zeitersparnis: Komplexe grenzüberschreitende Registrierungsprozesse, Netzwerkanforderungen und lokale Zahlungsbeschränkungen werden von uns übernommen.',
      'main.s2.s3.p2': 'Hohe Erfolgsrate: Wir verfügen über ausgereifte Registrierungslösungen und Ressourcen, um ein sauberes und stabiles ausländisches Steam-Konto zu gewährleisten.',
      'main.s2.s3.p3': 'Personalisierung: Sie können die Region auswählen, und wir können bei der ersten Aufladung oder dem Kauf helfen.',
      'main.s2.s4.title': '4. Balance Trading - Flexible und intelligente Aufladung!',
      'main.s2.s4.p1': 'Quellen: Steam Wallet-Balance aus Markttransaktionen, Steam-Geschenkkarten und anderen Kanälen.',
      'main.s2.s4.p2': 'Rabatte: Im Vergleich zu offiziellen Kanälen bieten Guthabenaufladungen oft attraktive Rabatte.',
      'Main.s2.s4.p3': 'Mehrere Verwendungen: Nutzen Sie das Guthaben für Spiele, DLC, Ingame-Artikel oder Marktteile – flexibel und bequem.',
      'main.s2.s5.title': 'Warum uns wählen?',
      'main.s2.s5.p1': 'Wir sind selbst Spieler und verstehen Ihre Bedürfnisse und Sorgen tiefgreifend.',
      'main.s2.s5.p2': 'Maximale Sicherheit: Die Sicherheit Ihres Kontos steht bei uns an erster Stelle, alle Prozesse sind transparent und nachvollziehbar.',
      'main.s2.s5.p3': 'Transparenz der Preise: Alle Kosten sind vor dem Kauf klar.',
      'main.s2.s5.p4': 'Professionelle Unterstützung: 24/7 Kundenservice-Team verfügbar.',
      'main.s2.s5.p5': 'Datenschutz: Wir verraten niemals persönliche oder Kontoinformationen.',
      'main.s2.s6.title': 'Risiken und Tipps',
      'main.s2.s6.p1': 'Wir sind sich der potenziellen politischen Risiken bewusst. Es wird empfohlen, ein sekundäres Konto für grenzüberschreitende Käufe zu verwenden und häufiges Kontoswitching oder große ungewöhnliche Transaktionen zu vermeiden.',
      'main.s2.s7.title': 'Handeln Sie jetzt!',
      'main.s2.s7.p1': 'Lassen Sie sich von Preis und Region beim Gaming nicht einschränken! Besuchen Sie GameGlobal und entdecken Sie eine neue Welt der Spiele. Registrieren Sie sich jetzt, um einen besonderen Neukunden-Gutschein zu erhalten!',


      'footer.notice':'Die Dienste richten sich nur an Benutzer, die Käufe in Niedrigpreis-Zonen benötigen. Bitte halten Sie sich an die lokalen Gesetze und Plattformbedingungen.',
      'footer.tos':'AGB & Datenschutz','dropdown.steamBalance':'Steam Guthaben',

      'dropdown.steamAccount':'Steam Konto',
      'dropdown.steamRegister':'Steam Registrierung',
      'dropdown.steamGift':'Steam Geschenk',
      'dropdown.contact':'Kontakt',
      'dropdown.about':'Über uns',
      'dropdown.comingSoon':'Bald verfügbar'},
      hi: { 'header.subtitle':'कम मूल्य क्षेत्र · छूट · बैलेंस',

      'nav.projects':'मुख्य परियोजनाएं', 'nav.support':'सहायता',

      'main.s1.title': 'सभी खिलाड़ियों को एक पत्र',
      'main.s1.p1': 'प्रिय खिलाड़ियों,',
      'main.s1.p2': 'क्या आप कभी अपने क्षेत्र के स्टीम स्टोर में उच्च कीमतों से निराश हुए हैं? क्या आपने कभी सीमित संस्करण या क्षेत्रीय सामग्री को याद किया है?  nक्या आपको विदेशी खातों का पंजीकरण जटिल और जोखिम भरा लगता है? ',
      'main.s1.p3': 'हम GameGlobal में आपकी चिंताओं को पूरी तरह से समझते हैं! हम अनुभवी गेमरों की एक टीम हैं जो क्षेत्रीय और मूल्य निर्धारण बाधाओं को तोड़ने के लिए समर्पित हैं, जिससे प्रत्येक खिलाड़ी को वै ',
      'main.s2.title': 'हम क्या पेशकश कर सकते हैं? ',
      'main.s2.p1': 'हम एक सुरक्षा ग्लोबल स्टीम प्लेटफॉर्म बना रहे हैं',
      'main.s2.s1.title': '1. वैश्विक उपहार खरीद - सबसे कम लागत, अधिकतम खेल! ',
      'main.s2.s1.p1': 'मुख्य लाभ: क्षेत्रों में मूल्य निर्धारण अंतरों का उपयोग करते हुए, हम कम कीमत वाले क्षेत्रों से गेम खरीदते हैं और उन्हें आधिक स्थानीय स्टोर की तुलना में बहुत सस्ता, पैसे बचाना महत्वपूर्ण है! ',
      'main.s2.s1.p2': 'सुरक्षा: सभी उपहार आधिकारिक स्टीम चैनलों के माध्यम से भेजे जाते हैं, स्पष्ट उत्पत्ति के साथ और काले बाजार के कोड का को ',
      'main.s2.s1.p3': 'सुविधा: बस अपना स्टीम प्रोफ़ाइल लिंक प्रदान करें, अपने गेम चुनें, भुगतान करें, और उपहारों का इंतजार करें! ',
      'main.s2.s2.title': '2. वैश्विक खाता बिक्री - दुनिया भर में खेलने के लिए तैयार! ',
      'main.s2.s2.p1': 'विविधता: हम कई क्षेत्रों में पंजीकृत स्टीम खाते प्रदान करते हैं। चाहे कम कीमत के गेम या क्षेत्र-विशेष सामग्री के लिए, हर किसी के लिए एक है। ',
      'main.s2.s2.p2': 'विश्वसनीयता: सभी खातों को सख्ती से सत्यापित किया जाता है, जानकारी पूरी होती है, प्रारंभिक ईमेल बदले जा सकते हैं, अधिकतम ख ',
      'main.s2.s2.p3': 'तत्काल उपयोग: तुरंत पूर्ण खाता विवरण प्राप्त करें और बिना देरी के अपनी वैश्विक गेमिंग यात्रा शुरू कर ',
      'main.s2.s3.title': '3. खाता पंजीकरण सेवा - इसे पेशेवरों को छोड़ दें! ',
      'main.s2.s3.p1': 'समय-बचत: जटिल क्रॉस-क्षेत्र पंजीकरण प्रक्रियाएं, नेटवर्क आवश्यकताएं और स्थानीय भुगतान सीमाएं सभी हमारे द्वार',
      'main.s2.s3.p2': 'उच्च सफलता दरः हमारे पास एक स्वच्छ, स्थिर विदेशी स्टीम खाता सुनिश्चित करने के लिए परिपक्व पंजीकरण समाधान ',
      'main.s2.s3.p3': 'निजीकरण: आप क्षेत्र का चयन कर सकते हैं, और हम प्रारंभिक रिचार्ज या खरीदारी में सहायता कर सकते हैं। ',
      'main.s2.s4.title': '4. बैलेंस ट्रेडिंग - लचीला और स्मार्ट रिचार्ज! ',
      'main.s2.s4.p1': 'स्रोत: बाजार ट्रेड, स्टीम उपहार कार्ड और अन्य चैनलों से स्टीम वॉलेट शेष राशि। ',
      'main.s2.s4.p2': 'छूट: आधिकारिक चैनलों की तुलना में, संतुलन टॉप-अप अक्सर आकर्षक छूट का आनंद लेते हैं। ',
      'main.s2.s4.p3': 'कई उपयोग: गेम, डीएलसी, इन-गेम आइटम, या बाजार खरीद के लिए संतुलन का उपयोग करें, लचीला और सुविधाजनक। ',
      'main.s2.s5.title': 'हमें क्यों चुनें? ',
      'main.s2.s5.p1': 'हम खुद खिलाड़ी हैं और आपकी आवश्यकताओं और चिंताओं को गहराई से समझते हैं। ',
      'main.s2.s5.p2': 'अधिकतम सुरक्षा: खाता सुरक्षा हमारी प्राथमिकता है, सभी प्रक्रियाएं पारदर्शी और ट्रेस योग्य हैं। ',
      'main.s2.s5.p3': 'पारदर्शी मूल्य निर्धारण: खरीद से पहले सभी लागत स्पष्ट हैं। ',
      'main.s2.s5.p4': 'पेशेवर सहायता: 24/7 ग्राहक सेवा टीम उपलब्ध है। ',
      'main.s2.s5.p5': 'गोपनीयता: हम कभी भी व्यक्तिगत या खाता जानकारी लीक नहीं करते हैं। ',
      'main.s2.s6.title': 'जोखिम और सुझाव',
      'main.s2.s6.p1': 'हम संभावित नीतिगत जोखिमों से अवगत हैं। क्षेत्र-क्षेत्र खरीद के लिए एक माध्यमिक खाते का उपयोग करने और अक्सर खाते स्विचिंग या बड़े असामान्य लेनदेन से बचने की सिफारिश क ',
      'main.s2.s7.title': 'अभी कार्य करें! ',
      'main.s2.s7.p1': 'कीमत और क्षेत्र को अपने गेमिंग को सीमित नहीं करने दें! GameGlobal पर जाएं और खेलों की एक नई दुनिया का पता लगाएं। एक विशेष नया उपयोगकर्ता कूपन प्राप्त करने के लिए अब पंजीकरण करें! ',


      'footer.notice':'सेवाएं केवल उन उपयोगकर्ताओं के लिए हैं जिन्हें कम मूल्य क्षेत्र की खरीद की आवश्यकता है। कृपया स्थानीय कानूनों और प्लेटफ़ॉर्म शर्तों का पालन करें।',
      'footer.tos':'नियम & गोपनीयता',

      'dropdown.steamBalance':'Steam बैलेंस',
      'dropdown.steamAccount':'Steam खाता',
      'dropdown.steamRegister':'Steam पंजीकरण',
      'dropdown.steamGift':'Steam गिफ्ट',
      'dropdown.contact':'संपर्क करें',
      'dropdown.about':'हमारे बारे में',
      'dropdown.comingSoon':'जल्द आ रहा है'},
      pt: { 'header.subtitle':'Zonas de baixo preço · Descontos · Saldo',

      'nav.projects':'Principais Projetos',
      'nav.support':'Suporte',

      'main.s1.title': 'Uma carta a todos os jogadores',
      'main.s1.p1': 'Queridos jogadores,',
      'main.s1.p2': 'Você já ficou desanimado pelos altos preços na loja Steam da sua região? Você já perdeu conteúdo em edição limitada ou regional? Você acha o registro de contas estrangeiras complicado e arriscado? ',
      'main.s1.p3': 'Nós na GameGlobal entendemos completamente suas preocupações! Somos uma equipe de jogadores experientes dedicados a quebrar barreiras regionais e de preços, permitindo que todos os jogadores desfrutem de jogos globalmente ao melhor preço e da maneira mais conveniente. ',
      'main.s2.title': 'O que podemos oferecer? ',
      'main.s2.p1': 'Estamos criando uma plataforma segura GlobalSteam',
      'main.s2.s1.title': '1. Compra de presente global - Custo mais baixo, jogos máximos! ',
      'main.s2.s1.p1': 'Vantagem principal: Utilizando diferenças de preços entre regiões, compramos jogos de zonas de baixo preço e os enviamos como presentes oficiais do Steam. Muito mais barato do que a loja local, poupar dinheiro é a chave! ',
      'main.s2.s1.p2': 'Segurança: Todos os presentes são enviados através dos canais oficiais do Steam, com origem clara e sem risco de códigos do mercado negro, garantindo a segurança da conta. ',
      'main.s2.s1.p3': 'Conveniência: basta fornecer o link do seu perfil Steam, escolher os seus jogos, pagar e esperar pelos presentes! ',
      'main.s2.s2.title': '2. Vendas de contas globais - Pronto para jogar em todo o mundo! ',
      'main.s2.s2.p1': 'Variedade: Oferecemos contas Steam registradas em várias regiões. Seja para jogos de baixo preço ou conteúdo exclusivo da região, há um para todos. ',
      'main.s2.s2.p2': 'Confiabilidade: Todas as contas são rigorosamente verificadas, informações completas, e-mails iniciais podem ser alterados, garantindo a máxima propriedade da conta e segurança. ',
      'main.s2.s2.p3': 'Uso instantâneo: Receba detalhes completos da conta imediatamente e comece sua jornada global de jogos sem demora. ',
      'main.s2.s3.title': '3. Serviço de Registro de Conta - Deixe para os Profissionais! ',
      'main.s2.s3.p1': 'Economia de tempo: Processos complexos de registro entre regiões, requisitos de rede e limitações de pagamento local são todos tratados por nós.',
      'main.s2.s3.p2': 'Alta taxa de sucesso: Temos soluções de registro maduras e recursos para garantir uma conta Steam estrangeira limpa e estável. ',
      'main.s2.s3.p3': 'Personalização: Você pode selecionar a região, e nós podemos ajudar com recarga inicial ou compras. ',
      'main.s2.s4.title': '4. Balance Trading - Recarga flexível e inteligente! ',
      'main.s2.s4.p1': 'Fontes: Saldos da Carteira Steam de negociações de mercado, cartões-presente Steam e outros canais. ',
      'main.s2.s4.p2': 'Descontos: Em comparação com os canais oficiais, as reposições de equilíbrio muitas vezes desfrutam de descontos atraentes. ',
      'main.s2.s4.p3': 'Usos múltiplos: Use o equilíbrio para jogos, DLC, itens no jogo ou compras no mercado, flexível e conveniente. ',
      'main.s2.s5.title': 'Por que nos escolher? ',
      'main.s2.s5.p1': 'Somos jogadores nós mesmos e compreendemos profundamente suas necessidades e preocupações. ',
      'main.s2.s5.p2': 'Máxima segurança: a segurança da conta é nossa prioridade, todos os processos são transparentes e rastreáveis. ',
      'main.s2.s5.p3': 'Preços transparentes: Todos os custos são claros antes da compra. ',
      'main.s2.s5.p4': 'Suporte profissional: equipa de atendimento ao cliente disponível 24/7. ',
      'main.s2.s5.p5': 'Privacidade: Nós nunca vazamos informações pessoais ou de conta. ',
      'main.s2.s6.title': 'Riscos e dicas',
      "main.s2.s6.p1": 'Estamos cientes dos potenciais riscos políticos. Recomenda-se usar uma conta secundária para compras entre regiões e evitar mudanças frequentes de conta ou grandes transações incomuns. ',
      'main.s2.s7.title': 'Agir agora! ',
      'main.s2.s7.p1': 'Não deixe que preço e região limitem seu jogo! Visite o GameGlobal e explore um novo mundo de jogos. Inscreva-se agora para receber um novo cupom especial! ',


      'footer.notice':'Os serviços destinam-se apenas a usuários que precisam de compras em zonas de baixo preço. Por favor, cumpra as leis locais e os termos da plataforma.',
      'footer.tos':'Termos & Privacidade',

      'dropdown.steamBalance':'Saldo Steam',
      'dropdown.steamAccount':'Conta Steam',
      'dropdown.steamRegister':'Registro Steam',
      'dropdown.steamGift':'Presente Steam',
      'dropdown.contact':'Contato','dropdown.about':'Sobre',
      'dropdown.comingSoon':'Em breve'},
      ru: { 'header.subtitle':'Зоны низких цен · Скидки · Баланс',

      'nav.projects':'Основные проекты',
      'nav.support':'Поддержка',

      'main.s1.title': 'Письмо всем игрокам',
      'main.s1.p1': 'Уважаемые игроки,',
      'main.s1.p2': 'Вас когда-нибудь разочаровали высокие цены в магазине Steam вашего региона? Вы когда-нибудь пропускали ограниченное издание или региональный контент? Считаете ли регистрацию иностранных счетов сложной и рискованной? ',
      'main.s1.p3': 'Мы в GameGlobal полностью понимаем ваши проблемы! Мы команда опытных игроков, посвященная преодолению региональных и ценовых барьеров, позволяющих каждому игроку наслаждаться играми по всему миру по лучшей цене и самым удобным способом. ',
      'main.s2.title': 'Что мы можем предложить? ',
      'main.s2.p1': 'Мы создаем безопасную платформу GlobalSteam',
      'main.s2.s1.title': '1. Глобальная покупка подарков - самые низкие цены, максимальные игры! ',
      'main.s2.s1.p1': 'Основное преимущество: Используя разницу цен между регионами, мы покупаем игры из низкоценовых зон и отправляем их в качестве официальных подарков Steam. Гораздо дешевле, чем местный магазин, экономия денег - это ключ! ',
      'main.s2.s1.p2': 'Безопасность: Все подарки отправляются через официальные каналы Steam, с четким происхождением и без риска черного рынка, обеспечивая безопасность учетной записи. ',
      'main.s2.s1.p3': 'Удобство: Просто предоставите ссылку на свой профиль в Steam, выберите свои игры, заплатите и ждите подарков! ',
      'main.s2.s2.title': '2. Глобальные продажи счетов - готовы играть по всему миру! ',
      'main.s2.s2.p1': 'Разнообразие: Мы предлагаем учетные записи Steam, зарегистрированные в нескольких регионах. Будь то дешевые игры или эксклюзивный контент для региона, есть один для каждого. ',
      'main.s2.s2.p2': 'Надежность: Все учетные записи строго проверяются, информация полна, первоначальные письма электронной почты могут быть изменены, обеспечивая максимальную собственность учетной записи и безопасность. ',
      'main.s2.s2.p3': 'Мгновенное использование: немедленно получайте полные данные учетной записи и немедленно начните свое глобальное игровое путешествие. ',
      'main.s2.s3.title': '3. Услуга регистрации учетных записей - Оставьте это профессионалам! ',
      'main.s2.s3.p1': 'Экономия времени: Сложные межрегиональные процессы регистрации, сетевые требования и ограничения местных платежей все решаются нами.',
      'main.s2.s3.p2': 'Высокий показатель успеха: У нас есть зрелые решения регистрации и ресурсы для обеспечения чистой и стабильной иностранной учетной записи Steam. ',
      'main.s2.s3.p3': 'Персонализация: Вы можете выбрать регион, и мы можем помочь с первоначальной зарядкой или покупками. ',
      'main.s2.s4.title': '4. Торговля балансом - гибкая и умная перезарядка! ',
      'main.s2.s4.p1': 'Источники: Балансы кошелька Steam из рыночных сделок, подарочных карт Steam и других каналов. ',
      'main.s2.s4.p2': 'Скидки: По сравнению с официальными каналами балансовые пополнения часто пользуются привлекательными скидками. ',
      'main.s2.s4.p3': 'Многочисленное использование: Используйте баланс для игр, DLC, предметов в игре или покупок на рынке, гибкий и удобный. ',
      'main.s2.s5.title': 'Почему выбрать нас? ',
      "main.s2.s5.p1": 'Мы сами игроки и глубоко понимаем ваши потребности и проблемы. ',
      'main.s2.s5.p2': 'Максимальная безопасность: безопасность учетной записи является нашим приоритетом, все процессы прозрачны и отслеживаемы. ',
      'main.s2.s5.p3': 'Прозрачное ценообразование: все расходы ясны до покупки. ',
      'main.s2.s5.p4': 'Профессиональная поддержка: 24/7 команда обслуживания клиентов доступна. ',
      'main.s2.s5.p5': 'Конфиденциальность: Мы никогда не раскрываем личную или учетную информацию. ',
      'main.s2.s6.title': 'Риски и советы',
      "main.s2.s6.p1": 'Мы осознаем потенциальные политические риски. Рекомендуется использовать вторичный счет для межрегиональных покупок и избегать частой смены счета или крупных необычных транзакций. ',
      'main.s2.s7.title': 'Действуйте сейчас! ',
      'main.s2.s7.p1': 'Не позволяйте цене и региону ограничивать вашу игру! Посетите GameGlobal и исследуйте новый мир игр. Зарегистрируйтесь сейчас, чтобы получить специальный купон для нового пользователя! ',


      'footer.notice':'Сервисы предназначены только для пользователей, которым нужны покупки в зонах низких цен. Пожалуйста, соблюдайте местные законы и условия платформы.',
      'footer.tos':'Условия & Конфиденциальность',

      'dropdown.steamBalance':'Баланс Steam',
      'dropdown.steamAccount':'Аккаунт Steam',
      'dropdown.steamRegister':'Регистрация Steam',
      'dropdown.steamGift':'Подарок Steam',
      'dropdown.contact':'Связаться',
      'dropdown.about':'О нас',
      'dropdown.comingSoon':'Скоро'}
    };

    const elements = document.querySelectorAll('[data-i18n]');
    const langSelect = document.getElementById('lang');

    function updateLanguage(lang){
      elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if(translations[lang] && translations[lang][key]){
          el.textContent = translations[lang][key];
        }
      });
    }

    langSelect.addEventListener('change', e => {
      updateLanguage(e.target.value);
    });

    updateLanguage(langSelect.value);



